config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root'searches#new'
  
  resources:posts do
    resources:comments
  end
  resources:searches
  resources:stores
  
  get '/about', to: 'pages#about'
  get '/label', to: 'pages#label'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    # if original post is deleted, the comments are deleted with the post
    has_many :comments, dependent: :destroy
    # sets a minimum input 
    validates :title, presence: true, length: { minimum: 5}
    validates :body, presence:true 
    
end

app/models/search.rb
class Search < ApplicationRecord#

    def search_stores
        # added conditions if keywords/category etc are present
        # compare the input with the search model and return indexed results from stores
        stores = Store.all
        
        stores = stores.where(["name LIKE ?","%#{keywords}%"]) if keywords.present?
        stores = stores.where(["category LIKE ?", category]) if category.present?
        stores = stores.where(["price_average >=  ?", min_price]) if min_price.present?
        stores = stores.where(["price_average <= ?", max_price]) if max_price.present?
        stores = stores.where(["source LIKE ?", source]) if source.present?
        stores = stores.where(["summary LIKE ?", summary]) if summary.present?
        
        return stores
    end
    

end

app/models/store.rb
class Store < ApplicationRecord
    has_attached_file :image, styles: { large: "600x600", medium: "300x300>", thumb: "150x150>#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    
    def self.search(search)
        # no longer being used
        # simple search that compares name input into search field with store indexes
        if search   
            where(["name LIKE ?","%#{search}%"])
        else
            all
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        
        # create comment method with name of user and body text
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name, :body))
        
        # redirects to all post page
        redirect_to post_path(@post)
	end
	
	def destroy
	    # find post id, find comment id on reference post, destroy
	    @post = Post.find(params[:post_id])
	    @comment = @post.comments.find(params[:id])
	    @comment.destroy
	    
	    redirect_to post_path(@post)
	end
end

app/controllers/pages_controller.rb
require 'nokogiri'
require 'open-uri'

class PagesController < ApplicationController
    def about
        #used to change the routing to /about
    end
   
  def label 
     # Nokogiri web scrape content from asos
     url = "https://marketplace.asos.com/boutiques/independent-label"

     doc = Nokogiri::HTML(open(url))
    # opens URL
     label = doc.css('#boutiqueList')
    # creates label with the correct css selector
     @label = label.css('#boutiqueList img').map { |l|  l.attr('src') }
     @title = label.css("#boutiqueList .notranslate").map { |o|  o.text }
     # saves all scraped content and maps it into an array
 end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    # Might use this if need strict permissions -  before_action :authenticate_user!, except: [:user, :show]
    # posts are ordered in descending order
    
    def index
        @posts = Post.all.order('created_at DESC')
    end
    # links new post
    def new
         @post = Post.new
    end
    # post creation and save
    def create
        @post = Post.new(post_params)
        # if post saved redirect to that post
        # if not saved render new.html.erb again
       if @post.save
            redirect_to @post
        else 
            render 'new'
          end  
        end
        # find post id and display contents
     def show
        @post = Post.find(params[:id])
    end
    
        def edit
        @post = Post.find(params[:id])
         end
         
            def update
                # if permissions and params met, update post
                 @post = Post.find(params[:id])
                 if @post.update(params[:post].permit(:title, :body))
                # redirect if correct, render edit page again if not
                 redirect_to @post
                    else
                     render 'edit'
                    end
                 end
    def destroy
        @post = Post.find(params[:id])
        # find post id, destroy and redirect to main post page
        @post.destroy
        
        redirect_to posts_path
    end
    
    # private define what parameters we are allowing
    
    private
    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    # searches unique to categories, needed for the dropdown menu and returning only index in that category
    def new
        @search = Search.new
        @categories = Store.uniq.pluck(:category)
        
        @counter = 1
    end
    # search create with the search parameters input
    def create 
        @search = Search.create(search_params)
        redirect_to @search
    end
    # search using the model logic to find the id of stores dependent on parameters
    def show
        @search = Search.find(params[:id])
    end
    
    private
    # parameters permitted in the search, if need all can be searched but only a couple parameters are searchable on HTML
    def search_params
        params.require(:search).permit(:keywords, :category, :min_price, :max_price, :source, :summary, :image)
    end
    
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.search(params[:search])
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :category, :price_average, :source, :summary, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
	    <!-- looping through comment.name, comment.body, date stamp -->
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>
	
	    <!-- adds method to button, links to comment controller -->
	    <% if user_signed_in? %>
	 	   <p> <%= link_to 'Delete', [comment.post, comment],
	       method: :delete,
	       class: "button",
	       data: { confirm: 'Are you sure?' }  %></p>
	  	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

     <!-- Form for inputing commenter name, comment and submission -->
     
	<%= f.label :name %><br>
	<%= f.text_field :name %><br>
	<br>
	
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br>
	
	<%= f.submit %>
	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clothing-rack</title>
    <%= csrf_meta_tags %>
		
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
<body>
	
  	<div id="sidebar">
		<div id="logo">
			<%= link_to new_search_path do %>
					<%= image_tag "" %>
			<% end %>
		</div>
		<ul>
			<li class="category">Clothing-Rack</li>
			<li><%= link_to "Boutique Search", new_search_path %></li>
			<li><%= link_to "Independent Labels", label_path %></li>
			<li><%= link_to "Blog", posts_path %></li>
			<li><%= link_to "About", about_path %></li>
			<!-- Does not appear when user is signed in -->
			<% if !user_signed_in? %>
			<li><%= link_to "Sign In", new_user_session_path %></li>
			<% end %>
			
			
		</ul>

		<ul>
			<li class="category">Other Links</li>
			<li><%= link_to "Sportstwear","http://gwarizm.com/", target: :_blank %></li>
			<li><%= link_to "Vintage","http://www.rokit.co.uk/blog", target: :_blank %></li>
			<li><%= link_to "Streetwear","http://agoraclothing.com/blog/", target: :_blank %></li> 
		</ul>
		<% if user_signed_in? %>
			<p class="sign_in">Admin</p>
		<% end %>
	</div>

<div id="main_content">
	
		<div id="header">
			<!-- header change depending on the current page -->
			<% if current_page?(posts_path) %>
				<p>All Posts</p>
				<% elsif current_page?(about_path) %>
				<p>About</p>
				<% elsif current_page?(new_search_path) %>
				<p>Boutique Search</p>
				<% elsif current_page? (root_path) %>
				<p>Boutique Search</p>
				<% elsif current_page?(label_path) %>
				<p>Independent Labels</p>
				<% else %>
			<!-- link back to boutique search when on show page -->
				<%= link_to "Back to Boutique Search", new_search_path %>
				<% end %>
				
			<% if user_signed_in? %>	
			<!-- buttons only visible when user signed in
						changed for Ubuntu firefox -->	
				<div class="buttons">
					<%= link_to "New Post", new_post_path, :class => "button" %>
					<%= link_to("Log Out", destroy_user_session_path, :class => "button", method: :delete) %>
				</div>
				<% end %>
				
		</div>
        
      <!-- flash button animation on buttons -->  
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>
		
		
		
		 <%= yield %>
			
   </div>
   
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "Closet.jpg" %>
		
		<%= image_tag "vintcloth.jpg" %>
	</div>

	<div id="content">
		<h1>Mission Statement</h1>
		
		
	</div>
	<p>Clothing-rack was created to be first and foremost a platform to promote <br>
	independent vintage boutiques and labels. With a central, constantly<br> changing and updated
	curated database it allows users to get a refined<br> look at what stores might be worth 
	checking out. We want to simplify<br> the process of searching for new labels and stores, by being the link<br> between the actual store
	page and the user. 
	We also want to create a <br> communal aspect, with blog posts about new stores added to the database, <br> current trends
	in fashion and miscellanious points of interest. Users can <br> comment via an anonymous system to add to the discussion or give
	their own <br> experience of a store.
	</p>

</div>

app/views/pages/label.html.erb
<!-- images scraped from web page and saved in vendor/images then moved to assets
    this was an alternative as my other web scraper cannot run with Heroku
    this is more of an illustration of what would have been
    
    imagescrape.rb is what was used to scrape these images
    
    with label2.html.erb - pages.controller and scrape2.rb housing the proper method
    that would have been utilised with arrays and loops -->
<div class="row">
    <div class="col-md-4">
        <div class="thumbnail">
            <%= link_to "https://marketplace.asos.com/boutique/wwyf", target: :_blank do %>
            <%= image_tag "wwyf.jpg" %>
            <% end %>
            <h4><%= link_to "WWYF", "https://marketplace.asos.com/boutique/wwyf", target: :_blank %></h4>
        </div>
    </div>
     <div class="col-md-4">
        <div class="thumbnail">
            <%= link_to "https://marketplace.asos.com/boutique/art-disco", target: :_blank do %>
            <%= image_tag "artdisc.jpg" %>
            <% end %>
            <h4><%= link_to "Art Disco","https://marketplace.asos.com/boutique/art-disco", target: :_blank %></h4>
        </div>
    </div>
    <div class="col-md-4">
        <div class="thumbnail">
            <%= link_to "https://marketplace.asos.com/boutique/duet", target: :_blank do %>
            <%= image_tag "duet.jpg" %>
            <% end %>
            <h4><%= link_to "Duet", "https://marketplace.asos.com/boutique/duet", target: :_blank %></h4>
        </div>
    </div>
     <div class="col-md-4">
        <div class="thumbnail">
            <%= link_to "https://marketplace.asos.com/boutique/ganga-shop", target: :_blank do %>
            <%= image_tag "lovers.jpg" %>
            <% end %>
            <h4><%= link_to "Ganga Shop", "https://marketplace.asos.com/boutique/ganga-shop", target: :_blank %></h4>
        </div>
      </div>
      <div class="col-md-4">
        <div class="thumbnail">
            <%= link_to "https://marketplace.asos.com/boutique/rqst", target: :_blank do %>
            <%= image_tag "rq.jpg" %>
            <% end %>
            <h4><%= link_to "R.Q.S.T", "https://marketplace.asos.com/boutique/rqst", target: :_blank %></h4>
        </div>
    </div>
    <div class="col-md-4">
        <div class="thumbnail">
            <%= link_to "https://marketplace.asos.com/boutique/flo-atelier", target: :_blank do %>
            <%= image_tag "flo.jpg" %>
            <% end %>
            <h4><%= link_to "Flo", "https://marketplace.asos.com/boutique/flo-atelier", target: :_blank %></h4>
        </div>
    </div>
      <div class="col-md-4">
        <div class="thumbnail">
            <%= link_to "https://marketplace.asos.com/boutique/tung", target: :_blank do %>
            <%= image_tag "tung.jpg" %>
            <% end %>
            <h4><%= link_to "Tung", "https://marketplace.asos.com/boutique/tung", target: :_blank %></h4>
        </div>
    </div>
    <div class="col-md-4">
        <div class="thumbnail">
            <%= link_to "https://marketplace.asos.com/boutique/blvck-clothing", target: :_blank do %>
            <%= image_tag "black.jpg" %>
            <% end %>
            <h4><%= link_to "BLVCK", "https://marketplace.asos.com/boutique/blvck-clothing", target: :_blank %></h4>
        </div>
    </div>
     <div class="col-md-4">
        <div class="thumbnail">
            <%= link_to "https://marketplace.asos.com/boutique/lily-and-the-lamplight", target: :_blank do %>
            <%= image_tag "lily.jpg" %>
            <% end %>
            <h4><%= link_to "Lily and the Lamplight", "https://marketplace.asos.com/boutique/lily-and-the-lamplight", target: :_blank %></h4>
        </div>
    </div>
    
 </div>

app/views/pages/label2.html.erb
<div class="row">
    <!-- calls in arrays with images and text from web scrape -->
  <% @label.each do |image| %>
  <% @title.each do |t| %>
    <div class="col-md-4">
        <div class="thumbnail">
            <div class="caption">
            <%= image_tag image %>
            <%= link_to t, "https://marketplace.asos.com/boutique/sisterhood" %>
            <!-- tester link -->
            </div>
        </div>
    </div>
<% end %>
<% end %>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div id="errors">
            <!-- if the either field is left empty, return an error -->
            <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
        <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>
     <p>
        <%= f.label :body %><br>
        <%= f.text_area :body %>
    </p>
    
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
    <h1>Edit Post</h1>
    
  <%=  render 'form' %>

</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<!-- display only title and date stamp and loop, so all posts are displayed that are indexed -->
		<h2 class="title"><%= link_to post.title, post %></h2>
		<br>
		<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
	</div>
<% end %>

    

app/views/posts/new.html.erb
<div id="page_wrapper">
    <h1>New Post</h1>
    
  <%=  render 'form' %>

</div>

app/views/posts/show.html.erb
<div id="post_content">
    <%= link_to "Back", posts_path %>
<h1 class= "title">
    <%= @post.title %>
</h1>

<p class= "date">
    <!-- edit and delete method on created a post with time created at -->
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
    <% if user_signed_in? %>
    <!-- only accessable to users signed in -->
    | <%= link_to 'Edit', edit_post_path(@post) %>
    | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
</p>

<p class= "body">
    <%= @post.body %>
</p>
    <div id="comments">
        <!-- grabbing comments.html.erb counts number of comments -->
        <h2><%= @post.comments.count %> Comments</h2>
        <%= render @post.comments %>
        
        
        <h3>Add a comment:</h3>
        <!-- renders the comment form for input -->
        <%= render "comments/form" %>
    </div>
</div>

app/views/searches/new.html.erb
<!--<div class="container">
    <!-- Page Content -->
    <div class="row">
        <div class="col-md-8">
            <% if @search.search_stores.empty? %>

                <p>No Records Found</p>
                
            <% else %>
            <div class="row">
                <% @search.search_stores.each do |c| %>
            
            
                <div class="col-md-6">
                    <div class="thumbnail">
                        <%= link_to c.source, target: :_blank do %>
                            <%= image_tag c.image.url(:medium) %>
                            <% end %>
                            <div class="caption">
                                <%= link_to c.source, target: :_blank do %>
                                <h4><%= c.name %></h4>
                                <% end %>
                                <h5 class="pull-right">Average Price £<%= c.price_average %></h5>
                                <h6><%= c.category %></h6>
                                <div class="ratings">
                                <p><%= c.summary %></p>
                                </div>
                                
                            </div>
                        </div>
                </div>
                
                <% end %> <!-- end search-->
            <% end %> <!-- end if statement-->
            </div>
            
            
            
        </div> <!-- end col-md-8 -->
        
    <div class="col-md-3 search-form">
            <%= form_for @search, html: {class: "pure-form"} do |s| %>
            <!-- search form -->
            <div class="field">
             <%= s.label :keywords %>
            <%= s.text_field :keywords %>
    </div>
    <div class="field">
        <!-- input for search parameters from model logic -->
        <br>
        <%= s.label :category %></>
        <%= s.select :category, options_for_select(@categories), :include_blank => true %>
    </div>
    <div class="field">
        <%= s.label :min_price, "Min Price" %>  <%= s.text_field :min_price, size: 10 %>
        <%= s.label :min_price, "Max Price" %>  <%= s.text_field :max_price, size: 10 %>
    </div>
    <br>
    <div class="actions"><%= s.submit "Search", class: "pure-button pure-button-primary" %></div>
    
<% end %>

</div><!--end col-md-4-->
</div> <!-- end row -->

</div> <!-- end container -->
<p><%= link_to 'Back', stores_path %></p>

app/views/searches/show.html.erb
<div class="row">
    
    <% @search.search_stores.each do |c| %>
        <div class="col-md-4">
            <div class="thumbnail">
               <%= link_to c.source, target: :_blank do %>
                 <%= image_tag c.image.url(:medium) %>
                    <% end %>
                    <div class="caption">
                    <h4><%= link_to c.name, c.source, target: :_blank %></h4>
                    <h5 class="pull-right">Average Price £<%= c.price_average %></h5
                    <h6><%= c.category %></h6>
                    <div class="ratings">
                    <p><%= c.summary %></p>
                </div>
                </div>
            </div>
        </div>
    <% end %>
</div>
<% if @search.search_stores.empty? %>

    <p>No Records Found</p>
    
<% else %>

    
<% end %> <!-- end if statement-->
 
                 
                 
                

app/views/stores/_form.html.erb
<%= form_for @store, html: { multipart: true } do |f| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :price_average %>
    <%= f.text_field :price_average %>
  </div>

  <div class="field">
    <%= f.label :source %>
    <%= f.text_field :source %>
  </div>

  <div class="field">
    <%= f.label :summary %>
    <%= f.text_field :summary %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Stores</h1>

<%= form_tag stores_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<%= link_to "Advanced Search", new_search_path %>
<!-- original search -->
<!-- table for categories and indexes of stores -->
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Price average</th>
      <th>Source</th>
      <th>Summary</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<!-- store table with loop to show all created -->


  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.category %></td>
        <td><%= store.price_average %></td>
        <td><%= store.source %></td>
        <td><%= store.summary %></td>
        <td><%= image_tag store.image.url(:thumb) %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>
<!-- render new form creation -->
<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>
<!-- show page of all created stores -->
<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @store.category %>
</p>

<p>
  <strong>Price average:</strong>
  <%= @store.price_average %>
</p>

<p>
  <strong>Source:</strong>
  <%= @store.source %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @store.summary %>
</p>


<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>